### ISSUE TITLE
Support mobile devices

### ISSUE THREAD

**Issue by rg-wood** [grislyeye/three-meet#1]

**Comment by rg-wood** [comment]
@abitsalihu I think this is the responsive issue you were talking about.

**Comment by abitsalihu** [comment]
@rg-wood yes, feel free to assign me. :)

**Comment by rg-wood** [comment]
@abitsalihu let me know if you need any help with this. Always happy to lend a hand or answer questions.

**Comment by abitsalihu** [comment]
@rg-wood I was actually gonna message you, I checked the code last night and saw the layout of it and that you already implemented a breaking point at somewhere around 789px, If we could talk over discord or somewhere with no interruption would be better as to ask share a few ideas and ask for some tips.

**Comment by rg-wood** [comment]
Pr: https://github.com/grislyeye/three-meet/pull/101
