### ISSUE TITLE
Sidebar does not disappear when clicking outside page

### ISSUE THREAD

**Issue by rg-wood** [grislyeye/three-meet#95]
Sidebar does not rollback when users are clicking outside the page content, in the gap between the content and the bottom and right-side of the screen.

That is, in the red border seen here:

<img width="1280" alt="Screenshot 2022-09-03 at 19 15 12" src="https://user-images.githubusercontent.com/37806009/188283322-c94b88aa-567b-4d24-b2f9-b2d5cf00dca5.png">

**Comment by abitsalihu** [comment]
Idk if you fixed this or not, but only in the Combat Rules page it does not work, on the rest works fine.

**Comment by rgladwell** [comment]
I think it's happening on any page where the content doesn't exceed the view height. For example:

https://three-meet.grislyeye.com/#/pages/backgrounds/index

**Comment by rg-wood** [comment]
I think it's happening on any page where the content doesn't exceed the view height. For example:

https://three-meet.grislyeye.com/#/pages/backgrounds/index

**Comment by rg-wood** [comment]
@abitsalihu is this happening for you in your browser for the above page?

**Comment by abitsalihu** [comment]
@rg-wood It is happening, I went into dev mode and put a border to the section part and it appears that if you click on the section part the nav will close, but if u click outside of the section part the nav will not respond to it, so maybe just increase the height of the section? Or check to add an event listener somewhere else

<img width="1437" alt="Screen Shot 2022-09-04 at 12 55 56" src="https://user-images.githubusercontent.com/94648837/188309854-bea78aac-139d-42ee-9c89-8e56d7e9aed4.png">

**Comment by rgladwell** [comment]
@abitsalihu I agree. On my to-do list.

**Comment by rgladwell** [comment]
Thanks for verifying for me.

**Comment by rg-wood** [comment]
@abitsalihu I agree. On my to-do list. Thanks for verifying.

**Comment by abitsalihu** [comment]
@rg-wood I managed to fix it in this particular page, if u want u can assign me this problem.

**Comment by rg-wood** [comment]
@abitsalihu Sure. Send me a PR and I'll review it ASAP.
